import { languages } from '@/i18n/settings'
import { ChildProps } from '@/types'
import { dir } from 'i18next'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const poppins = Poppins({
	weight: ['400', '500', '600', '700'],
	variable: '--font-poppins',
	subsets: ['latin'],
})

const inter = Inter({
	weight: ['100', '300', '400', '500', '700', '900'],
	variable: '--font-inter',
	subsets: ['latin'],
})

export async function generateStaticParams() {
	return languages.map(lng => ({ lng }))
}

export const metadata: Metadata = {
	title: 'Ar-Roziy Clinic',
	description: 'Generated by create next app',
	icons: {
		icon: '/logo/headLogo.svg',
	},
}

interface Props extends ChildProps {
	params: { lng: string }
}

export default function RootLayout({ children, params: { lng } }: Props) {
	return (
		<html lang={lng} dir={dir(lng)}>
			<body className={`${inter.variable} ${poppins.variable} antialiased`}>
				{children}
				<Toaster position='top-center' />
			</body>
		</html>
	)
}
